name: Add to Project
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    if: github.repository_owner == 'GameServerManagers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1

        with:
          project-url: https://github.com/orgs/GameServerManagers/projects/11
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: "type: game server request"
