name: Version Check
on:
  push:

permissions:
  contents: read

jobs:
  version-Check:
    if: github.repository_owner == 'GameServerManagers'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Version Check
        run: chmod +x .github/workflows/version-check.sh; .github/workflows/version-check.sh
